data: data/csv_labels/balanced.csv
label: data/softlabels/csv/balanced.csv
batch_size: 64
data_args:
    mode: Null
num_workers: 8
optimizer: AdamW
optimizer_args:
    lr: 0.01
scheduler_args:
    patience: 10
    factor: 0.1
early_stop: 5
epochs: 5 #changed from 15
itercv: 10000
save: best
model: CRNN
pretrained: pretrained_models/sre/model.pth #newly added
model_args: {}
outputpath: experiments/
transforms: [timemask, freqmask]
loss: FrameBCELoss #changed from FrameBCELoss